# we'll see how this try and exception works in the python 3 programming language